
/*------------------------------------------------------------------------
    File        : MotorcycleInterface
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : dkurapkis
    Created     : Sat Dec 31 22:17:25 EET 2016
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

INTERFACE decorator.MotorcycleInterface:  
    METHOD PUBLIC VOID createMotorcycle().
END INTERFACE.