 
 /*------------------------------------------------------------------------
    File        : SimpleMotorcycle
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : dkurapkis
    Created     : Sat Dec 31 22:17:38 EET 2016
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.
USING decorator.MotorcycleInterface.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS decorator.SimpleMotorcycle IMPLEMENTS MotorcycleInterface: 

    METHOD PUBLIC VOID createMotorcycle():
        
    END METHOD.
END CLASS.