
/*------------------------------------------------------------------------
    File        : MotorcycleInterface
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : dkurapkis
    Created     : Sun Nov 20 10:02:05 EET 2016
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

INTERFACE factory.MotorcycleInterface:  
  
END INTERFACE.